name: Run CI
on: [push, pull_request]
 
jobs:
 normal_ci:
     runs-on: ubuntu-latest
     steps:
       - name: Run normal CI
         run: echo "Running normal CI"
  
 pull_request_ci:
     runs-on: ubuntu-latest
     if: ${{ github.event_name== 'push' }}
     steps:
       - name: Run PR CI
         run: echo "Running PR only CI"
